# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ywfshsn1I_sV_qazfJ8YLM_IiB9q_p58
"""

!nvidia-smi

# Install method

!pip install ultralytics

from IPython import display
display.clear_output()

import ultralytics
ultralytics.checks()

from ultralytics import YOLO

from IPython.display import display, Image

from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/DATA

!ls

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/DATA

!yolo task=detect mode=train model=yolov8s.pt data= DATA.yml epochs=10 imgsz=224 plots=True

# Commented out IPython magic to ensure Python compatibility.
# %pwd

!ls /content/drive/MyDrive/DATA/runs/detect/train2

Image(filename='/content/drive/MyDrive/DATA/runs/detect/train2/confusion_matrix.png', width=600)

Image(filename='runs/detect/train2/results.png')

Image(filename='runs/detect/train2/val_batch0_pred.jpg',width=600)

Image(filename='runs/detect/train2/results.png',width=600)